--- Apache demo YAML
- hosts: db 
  remote_user: ansadmin 
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: mc
  tasks:
  - name: Install httpd service 
    yum :
      name: httpd
      state: latest
    notify: 
    - start httpd service
  handlers: 
  - name: start httpd service
    service: 
      name: httpd
      enabled: yes
      state: restarted
